name: Update org profile repo table

on:
  repository:
    types: [created, renamed, deleted, transferred, publicized, privatized]
  push:
    branches: [main]
    paths:
      - "scripts/**"
      - "profile/**"
      - ".github/workflows/**"
  repository_dispatch:
    types: [update-repo-table]
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update-table:
    uses: ./.github/workflows/update-org-readme-reusable.yml
